engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
exclude_paths:
  - ".eslintrc.js"
  - "jest.config.js"
  - "test/**"
  - "**/*.md"
  - ".editorconfig"
  - ".gitignore"
  - "package.json"
  - "yarn.lock"
